# Flyers example sentences, part 3 (w351-w477)
EX = [
    ("w351", "I want to act in the school play.", "act", "我想在學校的戲劇裡演戲。"),
    ("w352", "I agree with you. Let's go to the beach!", "agree", "我同意你，我們去海灘吧！"),
    ("w353", "A rabbit suddenly appeared from behind the tree.", "appeared", "一隻兔子突然從樹後面出現。"),
    ("w354", "Our train arrives at five o'clock.", "arrives", "我們的火車五點抵達。"),
    ("w355", "The film begins at seven.", "begins", "電影七點開始。"),
    ("w356", "I can't believe it! We won!", "believe", "真不敢相信！我們贏了！"),
    ("w357", "Can I borrow your pencil, please?", "borrow", "請問我可以借你的鉛筆嗎？"),
    ("w358", "Be careful! Don't break the glass.", "break", "小心！別把杯子打破了。"),
    ("w359", "Don't touch the oven. It will burn you.", "burn", "不要碰烤箱，會燙傷你。"),
    ("w360", "We're going to camp next to the lake.", "camp", "我們要在湖邊露營。"),
    ("w361", "I like to chat with my friends after school.", "chat", "我喜歡放學後和朋友聊天。"),
    ("w362", "Can you cut the cake into eight pieces?", "cut", "你可以把蛋糕切成八塊嗎？"),
    ("w363", "We cycle to the park on Sundays.", "cycle", "我們星期天騎腳踏車去公園。"),
    ("w364", "I can't decide which ice cream to choose.", "decide", "我無法決定要選哪一種冰淇淋。"),
    ("w365", "She wants to design clothes when she's older.", "design", "她長大以後想設計衣服。"),
    ("w366", "The sun disappeared behind the clouds.", "disappeared", "太陽躲到雲後面不見了。"),
    ("w367", "The party ends at nine o'clock.", "ends", "派對九點結束。"),
    ("w368", "Please take off your shoes before you enter the house.", "enter", "進屋前請先脫鞋。"),
    ("w369", "Can you explain this maths homework to me?", "explain", "你可以跟我解釋這份數學作業嗎？"),
    ("w370", "Let's explore the old castle!", "explore", "我們去探索那座古城堡吧！"),
    ("w371", "My little brother fell over and hurt his knee.", "fell over", "我弟弟跌倒，撞傷了膝蓋。"),
    ("w372", "I feel tired today.", "feel", "我今天覺得很累。"),
    ("w373", "Can you fetch my glasses from the kitchen?", "fetch", "你可以去廚房幫我拿眼鏡嗎？"),
    ("w374", "Let's find out what time the shop opens.", "find out", "我們去查查看那家店幾點開門。"),
    ("w375", "Finish your homework before you watch TV.", "Finish", "看電視之前先把功課做完。"),
    ("w376", "Follow me! I know the way.", "Follow", "跟著我！我知道路。"),
    ("w377", "Don't forget your umbrella!", "forget", "別忘了你的雨傘！"),
    ("w378", "What happened to your arm?", "happened", "你的手臂怎麼了？"),
    ("w379", "I hate cold weather.", "hate", "我討厭寒冷的天氣。"),
    ("w380", "Can you hear the birds singing?", "hear", "你聽得到鳥在唱歌嗎？"),
    ("w381", "I hope it's sunny tomorrow.", "hope", "我希望明天是晴天。"),
    ("w382", "Hurry! The bus is coming.", "Hurry", "快點！公車來了。"),
    ("w383", "My English is improving every day.", "improving", "我的英文每天都在進步。"),
    ("w384", "I want to invent a robot that can cook.", "invent", "我想發明一個會煮飯的機器人。"),
    ("w385", "You can keep this book. It's a present.", "keep", "這本書你可以留著，是送你的禮物。"),
    ("w386", "The plane landed at the airport.", "landed", "飛機在機場降落了。"),
    ("w387", "We leave for school at eight o'clock.", "leave", "我們八點出門上學。"),
    ("w388", "Let me help you with that bag.", "Let", "讓我幫你拿那個袋子。"),
    ("w389", "The cat likes to lie in the sun.", "lie", "貓喜歡躺在陽光下。"),
    ("w390", "Can you help me lift this box?", "lift", "你可以幫我抬這個箱子嗎？"),
    ("w391", "I look after my little sister when Mum is busy.", "look after", "媽媽忙的時候我會照顧妹妹。"),
    ("w392", "You look like your dad.", "look like", "你長得像你爸爸。"),
    ("w393", "Make sure you close the door.", "Make sure", "一定要把門關好。"),
    ("w394", "Do you mind if I open the window?", "mind", "你介意我打開窗戶嗎？"),
    ("w395", "Mix the flour and the eggs together.", "Mix", "把麵粉和蛋攪拌在一起。"),
    ("w396", "I'm going to post this letter to Grandma.", "post", "我要把這封信寄給奶奶。"),
    ("w397", "I prefer apples to bananas.", "prefer", "比起香蕉，我比較喜歡蘋果。"),
    ("w398", "Dad is preparing dinner in the kitchen.", "preparing", "爸爸正在廚房準備晚餐。"),
    ("w399", "Pull the door to open it.", "Pull", "把門拉開。"),
    ("w400", "Can you push me on the swing?", "push", "你可以推我盪鞦韆嗎？"),
    ("w401", "I can't remember his phone number.", "remember", "我記不得他的電話號碼。"),
    ("w402", "Can you repair my bike?", "repair", "你可以修我的腳踏車嗎？"),
    ("w403", "Listen and repeat after me.", "repeat", "仔細聽，然後跟著我唸。"),
    ("w404", "The fire fighter saved the cat from the tree.", "saved", "消防員把貓從樹上救了下來。"),
    ("w405", "That shop sells toys and games.", "sells", "那家店賣玩具和遊戲。"),
    ("w406", "Can you speak English?", "speak", "你會說英文嗎？"),
    ("w407", "We spend our summer holidays at the beach.", "spend", "我們在海灘度過暑假。"),
    ("w408", "We stayed at Grandma's house for a week.", "stayed", "我們在奶奶家住了一個星期。"),
    ("w409", "I study English at school.", "study", "我在學校學英文。"),
    ("w410", "Take your coat. It's cold.", "Take", "帶上你的外套，天氣很冷。"),
    ("w411", "I want to thank you for the lovely present.", "thank", "我要謝謝你送的可愛禮物。"),
    ("w412", "Please don't touch the paintings.", "touch", "請不要觸摸畫作。"),
    ("w413", "Turn right at the bank.", "Turn", "在銀行那裡右轉。"),
    ("w414", "Turn off the light when you leave the room.", "Turn off", "離開房間時把燈關掉。"),
    ("w415", "Can you turn on the TV, please?", "turn on", "請你打開電視好嗎？"),
    ("w416", "Can I use your computer?", "use", "我可以用你的電腦嗎？"),
    ("w417", "We visit our grandparents every Sunday.", "visit", "我們每個星期天去看爺爺奶奶。"),
    ("w418", "She whispered the answer in my ear.", "whispered", "她在我耳邊悄悄說出答案。"),
    ("w419", "The teacher whistled and the race started.", "whistled", "老師吹哨，賽跑開始了。"),
    ("w420", "I hope our team wins the match.", "wins", "我希望我們隊贏得比賽。"),
    ("w421", "I wish I could fly like a bird.", "wish", "真希望我能像鳥一樣飛。"),
    ("w422", "We swam across the river.", "across", "我們游過了那條河。"),
    ("w423", "I thought it was hard, but actually it was easy.", "actually", "我以為很難，但其實很簡單。"),
    ("w424", "We went to the park after lunch.", "after", "我們午餐後去了公園。"),
    ("w425", "I've already finished my homework.", "already", "我已經寫完功課了。"),
    ("w426", "I like football, and I also like tennis.", "also", "我喜歡足球，也喜歡網球。"),
    ("w427", "Has anyone seen my keys?", "anyone", "有人看到我的鑰匙嗎？"),
    ("w428", "Is there anything to eat?", "anything", "有什麼東西可以吃嗎？"),
    ("w429", "I can't find my pen anywhere.", "anywhere", "我到處都找不到我的筆。"),
    ("w430", "She works as a nurse at the hospital.", "as", "她在醫院當護士。"),
    ("w431", "My brother is as tall as my dad.", "as tall as", "我哥哥和我爸爸一樣高。"),
    ("w432", "I'm reading a great book at the moment.", "at the moment", "我現在正在看一本很棒的書。"),
    ("w433", "Go away! I'm busy.", "away", "走開！我正在忙。"),
    ("w434", "Wash your hands before dinner.", "before", "吃晚餐前要洗手。"),
    ("w435", "I made this cake by myself.", "by myself", "這個蛋糕是我自己做的。"),
    ("w436", "Can you do your homework by yourself?", "by yourself", "你可以自己做功課嗎？"),
    ("w437", "It rained during the night.", "during", "夜裡下了雨。"),
    ("w438", "Each student has got a dictionary.", "Each", "每個學生都有一本字典。"),
    ("w439", "Do you want anything else?", "else", "你還想要別的東西嗎？"),
    ("w440", "Have you ever seen a whale?", "ever", "你曾經看過鯨魚嗎？"),
    ("w441", "There are toys everywhere in my brother's room.", "everywhere", "我弟弟的房間到處都是玩具。"),
    ("w442", "I've got a few friends in this town.", "a few", "我在這個鎮上有幾個朋友。"),
    ("w443", "We waited for two hours.", "for", "我們等了兩個小時。"),
    ("w444", "How long have you lived here?", "How long", "你在這裡住多久了？"),
    ("w445", "If it rains, we'll stay at home.", "If", "如果下雨，我們就待在家裡。"),
    ("w446", "There's no milk, so let's have juice instead.", "instead", "沒有牛奶了，我們改喝果汁吧。"),
    ("w447", "I've just eaten my lunch.", "just", "我剛剛吃完午餐。"),
    ("w448", "I can speak a little English.", "a little", "我會說一點點英文。"),
    ("w449", "May I sit here, please?", "May", "請問我可以坐這裡嗎？"),
    ("w450", "Take an umbrella. It might rain.", "might", "帶把雨傘，可能會下雨。"),
    ("w451", "I don't have much time.", "much", "我沒有很多時間。"),
    ("w452", "No-one was at home when I called.", "No-one", "我打電話的時候沒有人在家。"),
    ("w453", "There's nowhere to sit on the bus.", "nowhere", "公車上沒有地方可以坐。"),
    ("w454", "Can I come with you? Of course!", "Of course", "我可以跟你去嗎？當然可以！"),
    ("w455", "I go swimming once a week.", "once", "我一個星期去游泳一次。"),
    ("w456", "This shoe is here, but where's the other one?", "other", "這隻鞋子在這裡，另一隻在哪裡？"),
    ("w457", "The plane flew over our house.", "over", "飛機從我們家上空飛過。"),
    ("w458", "Walk past the bank and turn left.", "past", "走過銀行後左轉。"),
    ("w459", "Perhaps it will snow tomorrow.", "Perhaps", "也許明天會下雪。"),
    ("w460", "The film was quite good.", "quite", "這部電影還不錯。"),
    ("w461", "You should go to bed early.", "should", "你應該早點睡覺。"),
    ("w462", "I've lived here since last summer.", "since", "我從去年夏天就住在這裡。"),
    ("w463", "It was raining, so we stayed at home.", "so", "下雨了，所以我們待在家裡。"),
    ("w464", "I left my bag somewhere in the park.", "somewhere", "我把包包忘在公園的某個地方了。"),
    ("w465", "See you soon!", "soon", "待會見！"),
    ("w466", "It's still raining.", "still", "還在下雨。"),
    ("w467", "It was such a lovely day!", "such", "真是美好的一天！"),
    ("w468", "Suddenly, the lights went out.", "Suddenly", "突然間，燈全熄了。"),
    ("w469", "We walked through the forest.", "through", "我們走過森林。"),
    ("w470", "Let's play together.", "together", "我們一起玩吧。"),
    ("w471", "I brush my teeth twice a day.", "twice", "我一天刷兩次牙。"),
    ("w472", "Wait here until I come back.", "until", "在這裡等到我回來。"),
    ("w473", "I usually walk to school.", "usually", "我通常走路上學。"),
    ("w474", "Mum was cooking while I was doing my homework.", "while", "我在寫功課時，媽媽正在煮飯。"),
    ("w475", "I will call you tomorrow.", "will", "我明天會打電話給你。"),
    ("w476", "I can't see without my glasses.", "without", "沒有眼鏡我就看不見。"),
    ("w477", "Have you finished your homework yet?", "yet", "你功課寫完了沒？"),
]
