# Flyers example sentences, part 2 (w160-w350)
EX = [
    ("w160", "My little brother watches cartoons on Saturday morning.", "cartoons", "我弟弟星期六早上看卡通。"),
    ("w161", "What's on the other channel?", "channel", "另一個頻道在播什麼？"),
    ("w162", "Grandpa taught me how to play chess.", "chess", "爺爺教我下西洋棋。"),
    ("w163", "I collect stamps from all over the world.", "collect", "我收集世界各地的郵票。"),
    ("w164", "We went to a pop concert in the park.", "concert", "我們去公園看了一場流行音樂會。"),
    ("w165", "He's playing the drum very loudly.", "drum", "他把鼓打得很大聲。"),
    ("w166", "There's a music festival in our town every summer.", "festival", "我們鎮上每年夏天都有音樂節。"),
    ("w167", "It's dark in the cave. Turn on your torch!", "torch", "洞穴裡很暗，打開你的手電筒！"),
    ("w168", "My grandpa plays golf every Sunday.", "golf", "我爺爺每個星期天打高爾夫球。"),
    ("w169", "The piano is my favourite instrument.", "instrument", "鋼琴是我最喜歡的樂器。"),
    ("w170", "I got an invitation to Katy's birthday party.", "invitation", "我收到凱蒂生日派對的邀請函。"),
    ("w171", "I want to join the swimming club.", "join", "我想加入游泳社。"),
    ("w172", "Mum is reading a magazine about cooking.", "magazine", "媽媽正在看一本烹飪雜誌。"),
    ("w173", "Our team won the football match!", "match", "我們隊贏了足球比賽！"),
    ("w174", "Let's meet at the café at four o'clock.", "meet", "我們四點在咖啡館碰面吧。"),
    ("w175", "I'm a member of the school chess club.", "member", "我是學校西洋棋社的社員。"),
    ("w176", "My sister listens to pop music all day.", "pop music", "我姊姊整天都在聽流行音樂。"),
    ("w177", "The winner of the race gets a prize.", "prize", "賽跑的冠軍會得到獎品。"),
    ("w178", "This TV programme is about animals in the ocean.", "programme", "這個電視節目在介紹海洋動物。"),
    ("w179", "This puzzle has got five hundred pieces.", "puzzle", "這幅拼圖有五百片。"),
    ("w180", "We made a sand pyramid on the beach.", "pyramid", "我們在海灘上堆了一座沙金字塔。"),
    ("w181", "Our class won the music quiz.", "quiz", "我們班贏了音樂問答比賽。"),
    ("w182", "Let's have a race to the tree!", "race", "我們來比賽跑到那棵樹吧！"),
    ("w183", "Dad likes loud rock music.", "rock music", "爸爸喜歡大聲的搖滾樂。"),
    ("w184", "What's the score? Is it two – one?", "score", "現在比數多少？是二比一嗎？"),
    ("w185", "We're going to ski in the mountains this winter.", "ski", "我們今年冬天要去山上滑雪。"),
    ("w186", "The children are sledging down the hill.", "sledging", "孩子們正坐雪橇滑下山坡。"),
    ("w187", "My brother threw a snowball at me!", "snowball", "我哥哥朝我丟了一顆雪球！"),
    ("w188", "I want a new snowboard for my birthday.", "snowboard", "我生日想要一塊新的滑雪板。"),
    ("w189", "Snowboarding is exciting, but it's difficult.", "Snowboarding", "單板滑雪很刺激，但是很難。"),
    ("w190", "We made a big snowman in the garden.", "snowman", "我們在花園裡堆了一個大雪人。"),
    ("w191", "The singer is dancing on the stage.", "stage", "歌手在舞台上跳舞。"),
    ("w192", "Put your clothes in the suitcase. We're leaving tomorrow.", "suitcase", "把衣服放進行李箱，我們明天出發。"),
    ("w193", "There are eleven players in a football team.", "team", "一支足球隊有十一名球員。"),
    ("w194", "We slept in a tent when we went camping.", "tent", "我們去露營的時候睡在帳篷裡。"),
    ("w195", "I can play this tune on the guitar.", "tune", "我會用吉他彈這首曲子。"),
    ("w196", "Dad is changing the tyre on the car.", "tyre", "爸爸正在換車子的輪胎。"),
    ("w197", "She plays the violin in the school concert.", "violin", "她在學校音樂會上拉小提琴。"),
    ("w198", "We play volleyball on the beach.", "volleyball", "我們在海灘上打排球。"),
    ("w199", "And the winner is... Sarah!", "winner", "冠軍是……莎拉！"),
    ("w200", "I get up at seven a.m. every day.", "a.m.", "我每天早上七點起床。"),
    ("w201", "We moved to this town two years ago.", "ago", "我們兩年前搬到這個鎮上。"),
    ("w202", "The leaves turn red and yellow in autumn.", "autumn", "秋天樹葉會變成紅色和黃色。"),
    ("w203", "Write the date of the party on the calendar.", "calendar", "把派對的日期寫在月曆上。"),
    ("w204", "This castle is five centuries old.", "centuries", "這座城堡已經有五百年的歷史。"),
    ("w205", "What's the date today?", "date", "今天是幾月幾號？"),
    ("w206", "I went to bed early because I was tired.", "early", "我很累，所以很早就上床睡覺。"),
    ("w207", "The film is two hours long.", "hours", "這部電影長兩個小時。"),
    ("w208", "How long does it take to get to school?", "How long", "去學校要花多久時間？"),
    ("w209", "Hurry up! We're late for school.", "late", "快一點！我們上學遲到了。"),
    ("w210", "I'm busy now. Can I call you later?", "later", "我現在很忙，晚點再打給你好嗎？"),
    ("w211", "We have lunch at midday.", "midday", "我們中午十二點吃午餐。"),
    ("w212", "Last night I went to bed at midnight.", "midnight", "我昨晚半夜十二點才睡覺。"),
    ("w213", "Wait a minute! I'm putting on my shoes.", "minute", "等一下！我正在穿鞋子。"),
    ("w214", "My birthday is next month.", "month", "我的生日在下個月。"),
    ("w215", "The shop closes at six p.m.", "p.m.", "這家店晚上六點關門。"),
    ("w216", "It's twenty past three.", "past", "現在是三點二十分。"),
    ("w217", "It's a quarter to nine. Let's go!", "quarter", "現在是八點四十五分，我們走吧！"),
    ("w218", "Flowers grow in spring.", "spring", "春天花兒會開。"),
    ("w219", "We go to the beach every summer.", "summer", "我們每年夏天都去海灘。"),
    ("w220", "What time is it?", "time", "現在幾點？"),
    ("w221", "We're going to the zoo tomorrow.", "tomorrow", "我們明天要去動物園。"),
    ("w222", "There's a good film on TV tonight.", "tonight", "今晚電視上有一部好電影。"),
    ("w223", "It snows a lot here in winter.", "winter", "這裡冬天常下雪。"),
    ("w224", "January is the first month of the year.", "January", "一月是一年的第一個月。"),
    ("w225", "February is the shortest month.", "February", "二月是最短的月份。"),
    ("w226", "My cousin's birthday is in March.", "March", "我表妹的生日在三月。"),
    ("w227", "It often rains in April.", "April", "四月常常下雨。"),
    ("w228", "School finishes in June.", "June", "學校在六月結束。"),
    ("w229", "We went camping in July.", "July", "我們七月去露營。"),
    ("w230", "It's very hot in August.", "August", "八月非常熱。"),
    ("w231", "The new school year starts in September.", "September", "新學年在九月開始。"),
    ("w232", "We wear costumes at the end of October.", "October", "十月底我們會穿上戲服。"),
    ("w233", "November is cold and foggy here.", "November", "這裡的十一月又冷又多霧。"),
    ("w234", "December is the last month of the year.", "December", "十二月是一年的最後一個月。"),
    ("w235", "The ambulance took him to the hospital.", "ambulance", "救護車把他送到醫院。"),
    ("w236", "I ride my bicycle to school.", "bicycle", "我騎腳踏車上學。"),
    ("w237", "The fire engine is big and red.", "fire engine", "消防車又大又紅。"),
    ("w238", "The journey to Grandma's house takes three hours.", "journey", "去奶奶家的路程要三個小時。"),
    ("w239", "Can you give me a lift to the station?", "lift", "你可以載我去車站嗎？"),
    ("w240", "Cars go very fast on the motorway.", "motorway", "車子在高速公路上開得很快。"),
    ("w241", "There are fifty passengers on the bus.", "passengers", "公車上有五十位乘客。"),
    ("w242", "The train to London leaves from platform two.", "platform", "往倫敦的火車從第二月台出發。"),
    ("w243", "He wants to drive a racing car.", "racing", "他想開賽車。"),
    ("w244", "The railway goes along the river.", "railway", "鐵路沿著河流延伸。"),
    ("w245", "The rocket is flying to the moon.", "rocket", "火箭正飛向月球。"),
    ("w246", "There are two astronauts in the spaceship.", "spaceship", "太空船裡有兩位太空人。"),
    ("w247", "We took a taxi to the airport.", "taxi", "我們搭計程車去機場。"),
    ("w248", "We went on a tour of the old castle.", "tour", "我們參觀了那座古城堡。"),
    ("w249", "There's a lot of traffic in the city today.", "traffic", "今天城裡的交通很擁擠。"),
    ("w250", "My bike has got a broken wheel.", "wheel", "我的腳踏車有一個輪子壞了。"),
    ("w251", "I can't see the hills because of the fog.", "fog", "因為起霧，我看不到山丘。"),
    ("w252", "It's foggy this morning, so drive slowly.", "foggy", "今天早上起霧，所以開慢一點。"),
    ("w253", "There was a big storm last night.", "storm", "昨晚有一場大暴風雨。"),
    ("w254", "My favourite actor is in this film.", "actor", "我最喜歡的演員有演這部電影。"),
    ("w255", "The artist is painting a picture of the sea.", "artist", "畫家正在畫一幅海的畫。"),
    ("w256", "The astronaut is walking on the moon.", "astronaut", "太空人正在月球上走路。"),
    ("w257", "Dad has got a small business in town.", "business", "爸爸在鎮上開了一間小公司。"),
    ("w258", "The businessman is talking on the phone.", "businessman", "那位商人正在講電話。"),
    ("w259", "She's a designer. She makes clothes.", "designer", "她是設計師，她做衣服。"),
    ("w260", "The engineer is building a new bridge.", "engineer", "工程師正在建一座新橋。"),
    ("w261", "The fire fighter is putting out the fire.", "fire fighter", "消防員正在滅火。"),
    ("w262", "What job do you want to do when you're older?", "job", "你長大以後想做什麼工作？"),
    ("w263", "The journalist is writing a story for the newspaper.", "journalist", "記者正在為報紙寫報導。"),
    ("w264", "The manager of the hotel is very friendly.", "manager", "這家旅館的經理非常親切。"),
    ("w265", "The mechanic is repairing our car.", "mechanic", "技工正在修我們的車。"),
    ("w266", "Dad has got a meeting at ten o'clock.", "meeting", "爸爸十點要開會。"),
    ("w267", "Grandpa watches the news every evening.", "news", "爺爺每天晚上看新聞。"),
    ("w268", "There's a photo of our school in the newspaper.", "newspaper", "報紙上有一張我們學校的照片。"),
    ("w269", "My aunt works in an office in the city.", "office", "我阿姨在城裡的辦公室工作。"),
    ("w270", "The photographer took a photo of our class.", "photographer", "攝影師幫我們班拍了一張照片。"),
    ("w271", "The pilot is flying the plane.", "pilot", "飛行員正在開飛機。"),
    ("w272", "The police officer helped the old woman across the road.", "police officer", "警察扶那位老太太過馬路。"),
    ("w273", "The queen is waving to the people.", "queen", "女王正在向大家揮手。"),
    ("w274", "The singer is singing a lovely song.", "singer", "歌手正在唱一首好聽的歌。"),
    ("w275", "The waiter brought us our pizza.", "waiter", "服務生把我們的披薩送來了。"),
    ("w276", "Open the window and let some air in.", "air", "打開窗戶讓空氣進來。"),
    ("w277", "We found a big cave in the mountain.", "cave", "我們在山裡發現一個大洞穴。"),
    ("w278", "It's very hot and dry in the desert.", "desert", "沙漠裡又熱又乾。"),
    ("w279", "The Earth goes around the sun.", "Earth", "地球繞著太陽轉。"),
    ("w280", "We should look after the environment.", "environment", "我們應該愛護環境。"),
    ("w281", "Where's the exit? I want to go out.", "exit", "出口在哪裡？我想出去。"),
    ("w282", "We sat around the fire and sang songs.", "fire", "我們圍坐在火堆旁唱歌。"),
    ("w283", "In the future, I want to travel to space.", "future", "將來我想去太空旅行。"),
    ("w284", "We walked up the hill and had a picnic.", "hill", "我們走上山丘去野餐。"),
    ("w285", "The plane is going to land in five minutes.", "land", "飛機再五分鐘就要降落了。"),
    ("w286", "Whales live in the ocean.", "ocean", "鯨魚住在海洋裡。"),
    ("w287", "Earth is the planet we live on.", "planet", "地球是我們居住的行星。"),
    ("w288", "There are frogs and fish in the pond.", "pond", "池塘裡有青蛙和魚。"),
    ("w289", "Astronauts travel into space in a rocket.", "space", "太空人搭火箭進入太空。"),
    ("w290", "He threw a stone into the river.", "stone", "他把一顆石頭丟進河裡。"),
    ("w291", "We crossed the stream on big stones.", "stream", "我們踩著大石頭走過小溪。"),
    ("w292", "There's a wonderful view of the sea from my window.", "view", "從我的窗戶可以看到很棒的海景。"),
    ("w293", "This table is made of wood.", "wood", "這張桌子是木頭做的。"),
    ("w294", "My grandma lives alone in a small house.", "alone", "我奶奶一個人住在一棟小房子裡。"),
    ("w295", "The circus was amazing!", "amazing", "馬戲團表演太精彩了！"),
    ("w296", "I'm bored. Let's play a game.", "bored", "我好無聊，我們來玩遊戲吧。"),
    ("w297", "Oh no! My glasses are broken.", "broken", "糟糕！我的眼鏡壞了。"),
    ("w298", "These pencils are very cheap.", "cheap", "這些鉛筆很便宜。"),
    ("w299", "It's dark outside. Turn on the light.", "dark", "外面很暗，把燈打開。"),
    ("w300", "The river is very deep here, so don't swim.", "deep", "這裡的河很深，所以不要游泳。"),
    ("w301", "This chocolate cake is delicious!", "delicious", "這個巧克力蛋糕好好吃！"),
    ("w302", "The fridge is empty. Let's go shopping.", "empty", "冰箱空了，我們去買東西吧。"),
    ("w303", "An elephant is an enormous animal.", "enormous", "大象是一種非常巨大的動物。"),
    ("w304", "Have we got enough chairs for all our friends?", "enough", "我們的椅子夠所有朋友坐嗎？"),
    ("w305", "Excellent work! All your answers are right.", "Excellent", "做得太好了！你全部都答對了。"),
    ("w306", "I'm so excited about our holiday!", "excited", "我對我們的假期好興奮！"),
    ("w307", "This watch is very expensive.", "expensive", "這支手錶非常貴。"),
    ("w308", "Is the station far from here?", "far", "車站離這裡遠嗎？"),
    ("w309", "Horses can run very fast.", "fast", "馬可以跑得非常快。"),
    ("w310", "The people next door are very friendly.", "friendly", "隔壁的人非常友善。"),
    ("w311", "The film was frightening, so I closed my eyes.", "frightening", "這部電影很可怕，所以我把眼睛閉上了。"),
    ("w312", "The bus is full. We have to wait for the next one.", "full", "公車滿了，我們得等下一班。"),
    ("w313", "This maths homework is very hard.", "hard", "這份數學作業好難。"),
    ("w314", "This box is too heavy for me to lift.", "heavy", "這個箱子太重了，我抬不起來。"),
    ("w315", "That mountain is very high.", "high", "那座山非常高。"),
    ("w316", "The medicine tastes horrible!", "horrible", "這個藥好難吃！"),
    ("w317", "It's important to drink lots of water.", "important", "多喝水很重要。"),
    ("w318", "I'm interested in dinosaurs.", "interested", "我對恐龍很有興趣。"),
    ("w319", "This book about space is very interesting.", "interesting", "這本關於太空的書很有趣。"),
    ("w320", "It was kind of you to help me.", "kind", "謝謝你好心幫我。"),
    ("w321", "Can I have a large orange juice, please?", "large", "請給我一杯大杯柳橙汁。"),
    ("w322", "My cat is lazy. It sleeps all day.", "lazy", "我的貓很懶，牠整天都在睡覺。"),
    ("w323", "My bag is light because it's empty.", "light", "我的包包很輕，因為裡面是空的。"),
    ("w324", "What a lovely dress!", "lovely", "多麼漂亮的洋裝啊！"),
    ("w325", "The bridge is very low, so the bus can't go under it.", "low", "這座橋很低，所以公車過不去。"),
    ("w326", "I won a prize! I'm so lucky!", "lucky", "我得獎了！我好幸運！"),
    ("w327", "One of my socks is missing.", "missing", "我的一隻襪子不見了。"),
    ("w328", "We're going on holiday next week.", "next", "我們下星期要去度假。"),
    ("w329", "The classroom is very noisy today.", "noisy", "今天教室裡非常吵。"),
    ("w330", "My teacher was pleased with my homework.", "pleased", "老師對我的作業很滿意。"),
    ("w331", "The poor dog was cold and hungry.", "poor", "那隻可憐的狗又冷又餓。"),
    ("w332", "Football is a very popular sport.", "popular", "足球是非常受歡迎的運動。"),
    ("w333", "Are you ready? Let's go!", "ready", "你準備好了嗎？我們走吧！"),
    ("w334", "The rich man has got three big houses.", "rich", "那個有錢人有三棟大房子。"),
    ("w335", "Holly and I are wearing the same dress!", "same", "荷莉和我穿著一樣的洋裝！"),
    ("w336", "I've got several friends in my new school.", "several", "我在新學校交了好幾個朋友。"),
    ("w337", "My cat's fur is very soft.", "soft", "我的貓的毛很軟。"),
    ("w338", "I've got a sore foot because my shoes are too small.", "sore", "我的腳很痛，因為鞋子太小了。"),
    ("w339", "Today is a special day. It's my birthday!", "special", "今天是特別的日子，是我的生日！"),
    ("w340", "There's a strange smell in the kitchen.", "strange", "廚房裡有一股奇怪的味道。"),
    ("w341", "Are you sure the shop is open?", "sure", "你確定那家店有開嗎？"),
    ("w342", "My bedroom is always tidy.", "tidy", "我的房間總是很整齊。"),
    ("w343", "The new cat was unfriendly at first.", "unfriendly", "新來的貓一開始不太友善。"),
    ("w344", "He was unhappy because he lost his toy.", "unhappy", "他很不開心，因為他把玩具弄丟了。"),
    ("w345", "It's unkind to laugh at other people.", "unkind", "嘲笑別人是不友善的。"),
    ("w346", "Your room is very untidy. Please clean it.", "untidy", "你的房間好亂，請整理一下。"),
    ("w347", "It's unusual to see snow here in spring.", "unusual", "春天在這裡看到雪很不尋常。"),
    ("w348", "Put on a warm coat. It's cold outside.", "warm", "穿上保暖的外套，外面很冷。"),
    ("w349", "We had a wonderful time at the beach.", "wonderful", "我們在海灘玩得非常開心。"),
    ("w350", "Mum is worried because my brother is late.", "worried", "媽媽很擔心，因為弟弟還沒回來。"),
]
