# Picture captions for 對或錯 (checked against each img/*.svg by eye):
# (id, caption that is TRUE for the word's own picture, Chinese, caption with one detail changed or None)
PIC = [
    ("w0", "The beetle is green.", "這隻甲蟲是綠色的。", "The beetle is red."),
    ("w1", "The butterfly has got blue wings.", "這隻蝴蝶有藍色的翅膀。", "The butterfly has got yellow wings."),
    ("w2", "This camel is standing.", "這隻駱駝站著。", "This camel is sleeping."),
    ("w4", "The dinosaur is green.", "這隻恐龍是綠色的。", "The dinosaur is purple."),
    ("w5", "The eagle is flying.", "老鷹正在飛。", "The eagle is swimming."),
    ("w9", "This insect is brown.", "這隻昆蟲是棕色的。", "This insect is blue."),
    ("w10", "There are two eggs in the nest.", "鳥巢裡有兩顆蛋。", "There are four eggs in the nest."),
    ("w11", "The octopus is red.", "這隻章魚是紅色的。", "The octopus is green."),
    ("w12", "The swan is white.", "這隻天鵝是白色的。", "The swan is black."),
    ("w13", "The tortoise is green.", "這隻陸龜是綠色的。", "The tortoise is pink."),
    ("w15", "This is a white wing.", "這是一隻白色的翅膀。", "This is a black wing."),
    ("w17", "This is one finger.", "這是一根手指。", "These are two fingers."),
    ("w21", "This is a bracelet.", "這是一條手鍊。", None),
    ("w22", "This costume is purple.", "這套戲服是紫色的。", "This costume is orange."),
    ("w23", "This is a gold crown.", "這是一頂金色的皇冠。", "This is a silver crown."),
    ("w24", "These gloves are blue.", "這雙手套是藍色的。", "These gloves are red."),
    ("w25", "This necklace is brown.", "這條項鍊是棕色的。", "This necklace is white."),
    ("w28", "This ring is silver.", "這枚戒指是銀色的。", "This ring is gold."),
    ("w29", "These sunglasses are black.", "這副太陽眼鏡是黑色的。", "These sunglasses are pink."),
    ("w30", "This is a blue trainer.", "這是一隻藍色的運動鞋。", "This is a red trainer."),
    ("w31", "The umbrella is purple.", "這把雨傘是紫色的。", "The umbrella is yellow."),
    ("w32", "The boy is wearing a uniform.", "這個男生穿著制服。", None),
    ("w35", "There are lots of red spots on the yellow paper.", "黃色的紙上有很多紅色的點點。", "There are lots of green spots on the yellow paper."),
    ("w36", "This insect is red with black spots.", "這隻昆蟲是紅色的，有黑色的點點。", "This insect is green with black spots."),
    ("w37", "There are red and blue stripes.", "有紅色和藍色的條紋。", "There are green and yellow stripes."),
    ("w38", "This is a striped T-shirt.", "這是一件條紋 T 恤。", "This is a spotted T-shirt."),
    ("w43", "This is a chocolate biscuit.", "這是一塊巧克力餅乾。", "This is a strawberry biscuit."),
    ("w44", "The butter is yellow.", "奶油是黃色的。", "The butter is pink."),
    ("w45", "There's cereal in the bowl.", "碗裡有穀片。", None),
    ("w46", "These chopsticks are red.", "這雙筷子是紅色的。", "These chopsticks are green."),
    ("w47", "This is a bag of flour.", "這是一袋麵粉。", "This is a bag of sugar."),
    ("w48", "This is a fork.", "這是一支叉子。", "This is a spoon."),
    ("w49", "This is honey.", "這是蜂蜜。", None),
    ("w50", "This jam is red.", "這罐果醬是紅色的。", "This jam is green."),
    ("w51", "This is a knife.", "這是一把刀子。", "This is a fork."),
    ("w52", "There's a fork and a knife next to the plate.", "盤子旁邊有一支叉子和一把刀子。", "There's a spoon next to the plate."),
    ("w53", "These olives are green.", "這些橄欖是綠色的。", "These olives are black."),
    ("w54", "This pepper is green.", "這顆甜椒是綠色的。", "This pepper is red."),
    ("w56", "This is a piece of pizza.", "這是一片披薩。", "This is a piece of cake."),
    ("w57", "This is salt.", "這是鹽。", None),
    ("w58", "This person is smelling a flower.", "這個人正在聞花。", "This person is eating a flower."),
    ("w60", "This is a spoon.", "這是一支湯匙。", "This is a knife."),
    ("w61", "This strawberry is red.", "這顆草莓是紅色的。", "This strawberry is blue."),
    ("w62", "There are six pieces of sugar.", "有六顆方糖。", "There are ten pieces of sugar."),
    ("w64", "This is yoghurt.", "這是優格。", None),
    ("w65", "This is a bandage.", "這是一片 OK 繃。", None),
    ("w66", "You can buy medicine here.", "這裡可以買藥。", "You can buy pizza here."),
    ("w68", "The boy is falling over.", "這個男生跌倒了。", "The boy is dancing."),
    ("w69", "This medicine is red and yellow.", "這顆藥是紅色和黃色的。", "This medicine is blue and green."),
    ("w70", "This is an x-ray.", "這是一張 X 光片。", None),
    ("w72", "This comb is purple.", "這把梳子是紫色的。", "This comb is orange."),
    ("w73", "This is a cooker.", "這是一台爐子。", None),
    ("w74", "This cushion is orange.", "這個靠墊是橘色的。", "This cushion is blue."),
    ("w75", "This is a diary.", "這是一本日記。", None),
    ("w77", "This is an envelope.", "這是一個信封。", None),
    ("w78", "This is a fridge.", "這是一台冰箱。", None),
    ("w79", "This is a gate.", "這是一扇大門。", None),
    ("w80", "This key is gold.", "這把鑰匙是金色的。", "This key is silver."),
    ("w82", "This is an oven.", "這是一台烤箱。", None),
    ("w83", "This is a computer screen.", "這是一個電腦螢幕。", None),
    ("w84", "This shampoo is purple.", "這瓶洗髮精是紫色的。", "This shampoo is green."),
    ("w85", "There are books on the shelf.", "架子上有書。", "There are shoes on the shelf."),
    ("w86", "This soap is pink.", "這塊肥皂是粉紅色的。", "This soap is blue."),
    ("w87", "There's a bird on this stamp.", "這張郵票上有一隻鳥。", "There's a fish on this stamp."),
    ("w89", "The girl is on a swing.", "這個女生在盪鞦韆。", "The girl is on a bike."),
    ("w90", "This telephone is red.", "這支電話是紅色的。", "This telephone is blue."),
    ("w107", "There's a plane at the airport.", "機場有一架飛機。", None),
    ("w108", "This is a bank.", "這是一間銀行。", None),
    ("w109", "This bridge is red.", "這座橋是紅色的。", "This bridge is green."),
    ("w110", "This castle has got red flags.", "這座城堡有紅色的旗子。", "This castle has got blue flags."),
    ("w115", "This is a factory.", "這是一座工廠。", None),
    ("w116", "There's a fire engine at the fire station.", "消防局裡有一輛消防車。", "There's a taxi at the fire station."),
    ("w119", "This is a hotel.", "這是一間旅館。", None),
    ("w124", "This is a museum.", "這是一間博物館。", None),
    ("w126", "There's a path through the grass.", "草地中間有一條小路。", None),
    ("w128", "This is a post office.", "這是一間郵局。", None),
    ("w129", "This is a restaurant.", "這是一間餐廳。", None),
    ("w131", "This is a skyscraper.", "這是一棟摩天大樓。", None),
    ("w133", "This is a stadium.", "這是一座體育場。", None),
    ("w135", "This is a theatre.", "這是一間劇院。", None),
    ("w140", "This backpack is red.", "這個背包是紅色的。", "This backpack is blue."),
    ("w141", "This bin is empty.", "這個垃圾桶是空的。", "This bin is full."),
    ("w142", "The children are in a running competition.", "孩子們在參加賽跑比賽。", "The children are in a swimming competition."),
    ("w143", "This dictionary is blue.", "這本字典是藍色的。", "This dictionary is red."),
    ("w144", "This flag is red.", "這面旗子是紅色的。", "This flag is yellow."),
    ("w146", "This is glue.", "這是膠水。", None),
    ("w155", "These scissors are red.", "這把剪刀是紅色的。", "These scissors are blue."),
    ("w156", "The student is wearing a black hat.", "這個學生戴著一頂黑色的帽子。", "The student is wearing a white hat."),
    ("w160", "There's a rabbit in this cartoon.", "這部卡通裡有一隻兔子。", "There's a cat in this cartoon."),
    ("w162", "This chess piece is black.", "這顆棋子是黑色的。", "This chess piece is white."),
    ("w164", "A woman is singing at this concert.", "一位女生在這場音樂會上唱歌。", "A man is singing at this concert."),
    ("w165", "This drum is red and white.", "這個鼓是紅色和白色的。", "This drum is green and white."),
    ("w167", "This is a torch.", "這是一支手電筒。", None),
    ("w172", "There's a woman on this magazine.", "這本雜誌上有一位女生。", "There's a dog on this magazine."),
    ("w177", "This prize is a gold cup.", "這個獎品是一座金色的獎盃。", "This prize is a silver cup."),
    ("w179", "This puzzle piece is green.", "這片拼圖是綠色的。", "This puzzle piece is red."),
    ("w182", "This flag is black and white.", "這面旗子是黑白色的。", "This flag is red and white."),
    ("w184", "The score is two – one.", "比數是二比一。", "The score is three – one."),
    ("w186", "This sledge is red.", "這台雪橇是紅色的。", "This sledge is blue."),
    ("w188", "This snowboard is orange.", "這塊滑雪板是橘色的。", "This snowboard is green."),
    ("w190", "The snowman has got a black hat.", "雪人戴著一頂黑色的帽子。", "The snowman has got a red hat."),
    ("w191", "This is a stage.", "這是一座舞台。", None),
    ("w192", "This suitcase is blue.", "這個行李箱是藍色的。", "This suitcase is yellow."),
    ("w194", "This tent is orange.", "這頂帳篷是橘色的。", "This tent is green."),
    ("w196", "This tyre is black.", "這個輪胎是黑色的。", "This tyre is white."),
    ("w197", "This is a violin.", "這是一把小提琴。", "This is a guitar."),
    ("w198", "This is a volleyball.", "這是一顆排球。", None),
    ("w199", "The winner is holding a gold cup.", "冠軍拿著一座金色的獎盃。", "The winner is holding a flag."),
    ("w200", "It's eight a.m.", "現在是早上八點。", "It's eight p.m."),
    ("w202", "The leaves are orange.", "葉子是橘色的。", "The leaves are green."),
    ("w211", "It's midday.", "現在是中午十二點。", "It's midnight."),
    ("w212", "It's midnight.", "現在是半夜十二點。", "It's midday."),
    ("w215", "It's eight p.m.", "現在是晚上八點。", "It's eight a.m."),
    ("w218", "There's a butterfly on the flowers.", "花上有一隻蝴蝶。", "There's a bird on the flowers."),
    ("w219", "There's a watermelon on the beach.", "海灘上有一顆西瓜。", "There's a pizza on the beach."),
    ("w220", "It's twelve o'clock.", "現在是十二點。", "It's six o'clock."),
    ("w222", "There's a moon over the house.", "房子上方有月亮。", "There's a sun over the house."),
    ("w223", "There's snow on the tree.", "樹上有雪。", "There are flowers on the tree."),
    ("w224", "It's January.", "現在是一月。", "It's June."),
    ("w225", "It's February.", "現在是二月。", "It's November."),
    ("w226", "It's March.", "現在是三月。", "It's May."),
    ("w227", "It's April.", "現在是四月。", "It's August."),
    ("w228", "It's June.", "現在是六月。", "It's January."),
    ("w229", "It's July.", "現在是七月。", "It's October."),
    ("w230", "It's August.", "現在是八月。", "It's April."),
    ("w231", "It's September.", "現在是九月。", "It's December."),
    ("w232", "It's October.", "現在是十月。", "It's July."),
    ("w233", "It's November.", "現在是十一月。", "It's February."),
    ("w234", "It's December.", "現在是十二月。", "It's September."),
    ("w235", "The ambulance is white and red.", "救護車是白色和紅色的。", "The ambulance is black and yellow."),
    ("w236", "This is a bicycle.", "這是一台腳踏車。", None),
    ("w237", "The fire engine is red.", "消防車是紅色的。", "The fire engine is blue."),
    ("w241", "There are three passengers on the bus.", "公車上有三位乘客。", "There are five passengers on the bus."),
    ("w242", "Two people are waiting on the platform.", "有兩個人在月台上等車。", "Four people are waiting on the platform."),
    ("w243", "This racing car is red.", "這輛賽車是紅色的。", "This racing car is blue."),
    ("w244", "This is a railway.", "這是一條鐵路。", None),
    ("w245", "The rocket is flying.", "火箭正在飛。", None),
    ("w246", "This is a spaceship.", "這是一艘太空船。", None),
    ("w247", "The taxi is yellow.", "這輛計程車是黃色的。", "The taxi is red."),
    ("w249", "The traffic lights are red, yellow and green.", "紅綠燈有紅色、黃色和綠色。", None),
    ("w250", "This is a wheel.", "這是一個輪子。", None),
    ("w253", "There's a storm.", "現在有暴風雨。", "It's sunny."),
    ("w255", "The artist is wearing a black hat.", "畫家戴著一頂黑色的帽子。", "The artist is wearing a red hat."),
    ("w256", "This is an astronaut.", "這是一位太空人。", None),
    ("w260", "The engineer is wearing a yellow hat.", "工程師戴著一頂黃色的帽子。", "The engineer is wearing a blue hat."),
    ("w261", "The fire fighter is wearing a red hat.", "消防員戴著一頂紅色的帽子。", "The fire fighter is wearing a green hat."),
    ("w263", "This journalist has got glasses.", "這位記者戴著眼鏡。", "This journalist has got a hat."),
    ("w265", "The mechanic is wearing a blue hat.", "技工戴著一頂藍色的帽子。", "The mechanic is wearing a red hat."),
    ("w266", "Three people are sitting at the table.", "有三個人坐在桌子旁。", "Five people are sitting at the table."),
    ("w268", "This is a newspaper.", "這是一份報紙。", None),
    ("w269", "There's a computer on the desk.", "桌上有一台電腦。", "There's a cat on the desk."),
    ("w270", "The photographer has got a camera.", "攝影師拿著一台相機。", "The photographer has got a guitar."),
    ("w271", "The pilot is wearing a black hat.", "飛行員戴著一頂黑色的帽子。", "The pilot is wearing a white hat."),
    ("w272", "The police officer is wearing a blue hat.", "警察戴著一頂藍色的帽子。", "The police officer is wearing a red hat."),
    ("w273", "The queen is wearing a gold crown.", "女王戴著一頂金色的皇冠。", "The queen is wearing a silver crown."),
    ("w274", "The singer has got red hair.", "這位歌手有紅色的頭髮。", "The singer has got black hair."),
    ("w275", "The waiter is carrying a plate.", "服務生端著一個盤子。", "The waiter is carrying a box."),
    ("w278", "It's hot and sunny in the desert.", "沙漠裡又熱又晴朗。", None),
    ("w279", "This is the Earth.", "這是地球。", None),
    ("w282", "This is a fire.", "這是一團火。", None),
    ("w284", "There's a tree on the hill.", "山丘上有一棵樹。", "There's a house on the hill."),
    ("w286", "This is the ocean.", "這是海洋。", None),
    ("w287", "This planet has got a ring.", "這顆行星有一圈光環。", None),
    ("w289", "There are lots of stars in space.", "太空中有很多星星。", None),
    ("w290", "This stone is grey.", "這顆石頭是灰色的。", "This stone is pink."),
    ("w291", "There are stones in the stream.", "小溪裡有石頭。", "There are fish in the stream."),
    ("w293", "This is wood.", "這是木頭。", None),
]
