# Flyers example sentences, part 1 (w0-w159): (id, sentence, highlighted text, Chinese)
EX = [
    ("w0", "A black beetle is walking on the leaf.", "beetle", "一隻黑色的甲蟲在葉子上走。"),
    ("w1", "The butterfly has got orange and black wings.", "butterfly", "這隻蝴蝶有橘色和黑色的翅膀。"),
    ("w2", "The camel can walk across the desert for days.", "camel", "駱駝可以穿越沙漠走好幾天。"),
    ("w3", "We found a strange creature in the pond.", "creature", "我們在池塘裡發現一隻奇怪的生物。"),
    ("w4", "This dinosaur was bigger than a bus!", "dinosaur", "這隻恐龍比公車還大！"),
    ("w5", "The eagle is flying high above the mountains.", "eagle", "老鷹在高山上空飛翔。"),
    ("w6", "Dinosaurs are extinct, so we can only see them in museums.", "extinct", "恐龍已經絕種了，所以我們只能在博物館看到牠們。"),
    ("w7", "My cat has got soft white fur.", "fur", "我的貓有柔軟的白色毛。"),
    ("w8", "The rabbit is small and furry.", "furry", "這隻兔子小小的、毛茸茸的。"),
    ("w9", "A bee is an insect with six legs.", "insect", "蜜蜂是有六隻腳的昆蟲。"),
    ("w10", "There are three eggs in the bird's nest.", "nest", "鳥巢裡有三顆蛋。"),
    ("w11", "An octopus has got eight long arms.", "octopus", "章魚有八隻長長的腳。"),
    ("w12", "A white swan is swimming on the lake.", "swan", "一隻白天鵝在湖上游泳。"),
    ("w13", "The tortoise is very old and very slow.", "tortoise", "這隻陸龜很老，走得很慢。"),
    ("w14", "Lions and tigers are wild animals.", "wild", "獅子和老虎是野生動物。"),
    ("w15", "The bird hurt its wing, so it can't fly.", "wing", "這隻鳥的翅膀受傷了，所以不能飛。"),
    ("w16", "I fell off my bike and hurt my elbow.", "elbow", "我從腳踏車上摔下來，撞傷了手肘。"),
    ("w17", "She's wearing a ring on her finger.", "finger", "她的手指上戴著戒指。"),
    ("w18", "He's got a bandage on his knee.", "knee", "他的膝蓋上包著繃帶。"),
    ("w19", "The water is cold! I can feel it with my toes.", "toes", "水好冰！我的腳趾感覺得到。"),
    ("w20", "Dad is wearing a brown belt with his jeans.", "belt", "爸爸的牛仔褲搭配一條棕色皮帶。"),
    ("w21", "My aunt gave me a silver bracelet for my birthday.", "bracelet", "阿姨送我一條銀手鍊當生日禮物。"),
    ("w22", "I'm wearing a pirate costume to the party.", "costume", "我穿著海盜裝去參加派對。"),
    ("w23", "The queen has got a gold crown on her head.", "crown", "女王頭上戴著金色的皇冠。"),
    ("w24", "It's cold, so put on your gloves.", "gloves", "天氣很冷，戴上你的手套。"),
    ("w25", "Mum is wearing a beautiful necklace tonight.", "necklace", "媽媽今晚戴著一條漂亮的項鍊。"),
    ("w26", "It's time for bed. Put on your pyjamas!", "pyjamas", "該睡覺了，穿上你的睡衣！"),
    ("w27", "I've got a key in my pocket.", "pocket", "我的口袋裡有一把鑰匙。"),
    ("w28", "The queen is wearing a gold ring.", "ring", "女王戴著一枚金戒指。"),
    ("w29", "It's very sunny today. Where are my sunglasses?", "sunglasses", "今天太陽好大，我的太陽眼鏡在哪裡？"),
    ("w30", "I wear my trainers when I play basketball.", "trainers", "我打籃球的時候穿運動鞋。"),
    ("w31", "Take an umbrella. It's going to rain.", "umbrella", "帶把雨傘，快要下雨了。"),
    ("w32", "At my school, we wear a blue uniform.", "uniform", "我們學校穿藍色的制服。"),
    ("w33", "The winner got a gold cup.", "gold", "冠軍得到一座金色的獎盃。"),
    ("w34", "Grandma has got a silver watch.", "silver", "奶奶有一支銀色的手錶。"),
    ("w35", "There's a spot of paint on your T-shirt.", "spot", "你的 T 恤上有一個油漆點。"),
    ("w36", "I've got a red spotted umbrella.", "spotted", "我有一把紅色的點點雨傘。"),
    ("w37", "The tiger has got black stripes.", "stripes", "老虎有黑色的條紋。"),
    ("w38", "He's wearing a blue and white striped shirt.", "striped", "他穿著一件藍白條紋的襯衫。"),
    ("w39", "Her husband is a doctor at the hospital.", "husband", "她的丈夫是醫院的醫生。"),
    ("w40", "My aunt and uncle got married last summer.", "married", "我的阿姨和姨丈去年夏天結婚了。"),
    ("w41", "My surname is Brown, like my dad's.", "surname", "我姓布朗，跟我爸爸一樣。"),
    ("w42", "Mr Brown and his wife live next to us.", "wife", "布朗先生和他的太太住在我們隔壁。"),
    ("w43", "Can I have a chocolate biscuit, please?", "biscuit", "請問我可以吃一塊巧克力餅乾嗎？"),
    ("w44", "I like butter and jam on my bread.", "butter", "我喜歡在麵包上塗奶油和果醬。"),
    ("w45", "I eat cereal with milk for breakfast.", "cereal", "我早餐吃加牛奶的穀片。"),
    ("w46", "Can you eat noodles with chopsticks?", "chopsticks", "你會用筷子吃麵嗎？"),
    ("w47", "We need flour, eggs and sugar to make a cake.", "flour", "做蛋糕需要麵粉、蛋和糖。"),
    ("w48", "Please put a knife and fork on the table.", "fork", "請把刀子和叉子放在桌上。"),
    ("w49", "Bees make honey.", "honey", "蜜蜂會釀蜂蜜。"),
    ("w50", "Grandma makes strawberry jam.", "jam", "奶奶會做草莓果醬。"),
    ("w51", "Be careful! Don't cut your finger with that knife.", "knife", "小心！別被那把刀割到手指。"),
    ("w52", "Breakfast is my favourite meal of the day.", "meal", "早餐是我一天中最喜歡的一餐。"),
    ("w53", "There are green olives on the pizza.", "olives", "披薩上有綠橄欖。"),
    ("w54", "Can you give me the salt and pepper?", "pepper", "可以把鹽和胡椒給我嗎？"),
    ("w55", "Would you like a piece of cake?", "piece", "你想吃一塊蛋糕嗎？"),
    ("w56", "We're having pizza for dinner tonight.", "pizza", "我們今天晚餐吃披薩。"),
    ("w57", "This soup needs some salt.", "salt", "這碗湯需要加點鹽。"),
    ("w58", "The bread smells lovely.", "smells", "麵包聞起來好香。"),
    ("w59", "I have a snack after school.", "snack", "我放學後會吃點心。"),
    ("w60", "You need a spoon to eat your soup.", "spoon", "喝湯要用湯匙。"),
    ("w61", "This strawberry is big and red.", "strawberry", "這顆草莓又大又紅。"),
    ("w62", "Do you want sugar in your tea?", "sugar", "你的茶要加糖嗎？"),
    ("w63", "This soup tastes delicious!", "tastes", "這碗湯嚐起來好好喝！"),
    ("w64", "I like strawberry yoghurt.", "yoghurt", "我喜歡草莓優格。"),
    ("w65", "The nurse put a bandage on my arm.", "bandage", "護士在我的手臂上包了繃帶。"),
    ("w66", "Mum bought some medicine at the chemist's.", "chemist's", "媽媽在藥局買了一些藥。"),
    ("w67", "I've got a cut on my finger.", "cut", "我的手指上有一道傷口。"),
    ("w68", "Be careful on the ice or you'll fall over.", "fall over", "在冰上要小心，不然會跌倒。"),
    ("w69", "Take this medicine and you'll feel better.", "medicine", "吃了這個藥你就會好一點。"),
    ("w70", "The doctor looked at the x-ray of my leg.", "x-ray", "醫生看了我腿部的 X 光片。"),
    ("w71", "Brush your teeth before you go to bed.", "Brush", "睡覺前要刷牙。"),
    ("w72", "She combs her long hair every morning.", "combs", "她每天早上梳她的長髮。"),
    ("w73", "Dad is making soup on the cooker.", "cooker", "爸爸正在爐子上煮湯。"),
    ("w74", "There's a soft cushion on the sofa.", "cushion", "沙發上有一個軟軟的靠墊。"),
    ("w75", "I write in my diary every night.", "diary", "我每天晚上寫日記。"),
    ("w76", "Meet me at the entrance of the zoo.", "entrance", "在動物園的入口和我碰面。"),
    ("w77", "Put the letter in an envelope.", "envelope", "把信放進信封裡。"),
    ("w78", "The milk is in the fridge.", "fridge", "牛奶在冰箱裡。"),
    ("w79", "Close the gate, or the dog will run away.", "gate", "把大門關上，不然狗會跑走。"),
    ("w80", "I can't find the key to the front door.", "key", "我找不到前門的鑰匙。"),
    ("w81", "I wrote a letter to my grandpa.", "letter", "我寫了一封信給爺爺。"),
    ("w82", "The cake is in the oven.", "oven", "蛋糕在烤箱裡。"),
    ("w83", "Don't sit too near the screen.", "screen", "不要坐得離螢幕太近。"),
    ("w84", "I wash my hair with shampoo.", "shampoo", "我用洗髮精洗頭。"),
    ("w85", "Put the books back on the shelf, please.", "shelf", "請把書放回架子上。"),
    ("w86", "Wash your hands with soap and water.", "soap", "用肥皂和水洗手。"),
    ("w87", "You need a stamp to post this letter.", "stamp", "要寄這封信需要貼郵票。"),
    ("w88", "Sit on the step and take off your shoes.", "step", "坐在台階上把鞋子脫掉。"),
    ("w89", "The children are playing on the swings.", "swings", "孩子們在玩盪鞦韆。"),
    ("w90", "The telephone is ringing. Can you answer it?", "telephone", "電話響了，你可以接一下嗎？"),
    ("w91", "Betty is the oldest girl in our class.", "Betty", "貝蒂是我們班上年紀最大的女生。"),
    ("w92", "David likes playing chess with his dad.", "David", "大衛喜歡和爸爸下西洋棋。"),
    ("w93", "Emma wants to be a pilot one day.", "Emma", "艾瑪希望有一天能當飛行員。"),
    ("w94", "Frank is learning to play the drums.", "Frank", "法蘭克正在學打鼓。"),
    ("w95", "George forgot his backpack at school.", "George", "喬治把書包忘在學校了。"),
    ("w96", "Harry is the fastest runner in the team.", "Harry", "哈利是隊上跑得最快的人。"),
    ("w97", "Helen sent me a letter from London.", "Helen", "海倫從倫敦寄了一封信給我。"),
    ("w98", "Holly has got a big spotted dog.", "Holly", "荷莉有一隻大斑點狗。"),
    ("w99", "Katy is wearing a costume for the festival.", "Katy", "凱蒂為了節慶活動穿上戲服。"),
    ("w100", "Michael wants to be an astronaut.", "Michael", "麥可想當太空人。"),
    ("w101", "Oliver lives near the airport.", "Oliver", "奧利佛住在機場附近。"),
    ("w102", "Richard is good at maths.", "Richard", "理查的數學很好。"),
    ("w103", "Robert broke his arm last winter.", "Robert", "羅伯特去年冬天摔斷了手臂。"),
    ("w104", "Sarah won a prize in the competition.", "Sarah", "莎拉在比賽中得了獎。"),
    ("w105", "Sophia is studying history in the library.", "Sophia", "蘇菲亞正在圖書館讀歷史。"),
    ("w106", "William plays the violin in the school concert.", "William", "威廉在學校音樂會上拉小提琴。"),
    ("w107", "We're going to the airport to catch a plane.", "airport", "我們要去機場搭飛機。"),
    ("w108", "My aunt works in a bank in the city.", "bank", "我阿姨在城裡的銀行工作。"),
    ("w109", "We walked across the bridge over the river.", "bridge", "我們走過河上的橋。"),
    ("w110", "The queen lives in a big castle.", "castle", "女王住在一座大城堡裡。"),
    ("w111", "I go to a chess club on Fridays.", "club", "我每週五去參加西洋棋社。"),
    ("w112", "My big sister studies art at college.", "college", "我姊姊在學院讀藝術。"),
    ("w113", "The bank is on the corner of the street.", "corner", "銀行在這條街的轉角。"),
    ("w114", "The sun comes up in the east.", "east", "太陽從東方升起。"),
    ("w115", "My uncle works in a car factory.", "factory", "我叔叔在汽車工廠工作。"),
    ("w116", "The fire engine is at the fire station.", "fire station", "消防車在消防局裡。"),
    ("w117", "Let's sit at the front of the bus.", "front", "我們坐在公車的前面吧。"),
    ("w118", "How do I get to the museum?", "get to", "請問博物館怎麼去？"),
    ("w119", "We stayed in a hotel near the beach.", "hotel", "我們住在海灘附近的旅館。"),
    ("w120", "My school is two kilometres from my house.", "kilometres", "我的學校離我家兩公里。"),
    ("w121", "Turn left at the end of the street.", "left", "在這條街的盡頭左轉。"),
    ("w122", "London is a big city with lots of museums.", "London", "倫敦是一座有很多博物館的大城市。"),
    ("w123", "There's a big tree in the middle of the park.", "middle", "公園的中間有一棵大樹。"),
    ("w124", "We saw a dinosaur at the museum.", "museum", "我們在博物館看到恐龍。"),
    ("w125", "It's very cold in the north in winter.", "north", "冬天北方非常冷。"),
    ("w126", "Follow the path through the forest.", "path", "沿著小路穿過森林。"),
    ("w127", "The police officer took us to the police station.", "police station", "警察帶我們去警察局。"),
    ("w128", "I'm going to the post office to buy some stamps.", "post office", "我要去郵局買郵票。"),
    ("w129", "We had pizza at a restaurant near the beach.", "restaurant", "我們在海灘附近的餐廳吃披薩。"),
    ("w130", "The library is on the right.", "right", "圖書館在右邊。"),
    ("w131", "You can see the city from the skyscraper.", "skyscraper", "從摩天大樓上可以看到整座城市。"),
    ("w132", "Birds fly south in the autumn.", "south", "鳥兒在秋天往南飛。"),
    ("w133", "Thousands of people watched the match at the stadium.", "stadium", "好幾千人在體育場看比賽。"),
    ("w134", "Go straight on and the park is in front of you.", "straight on", "一直往前走，公園就在你前面。"),
    ("w135", "We saw a play at the theatre.", "theatre", "我們在劇院看了一齣戲。"),
    ("w136", "My cousin is a student at the university.", "university", "我的表哥是這所大學的學生。"),
    ("w137", "Is this the way to the station?", "way", "這是去車站的路嗎？"),
    ("w138", "The sun goes down in the west.", "west", "太陽從西方落下。"),
    ("w139", "Art is my favourite subject because I love painting.", "Art", "美術是我最喜歡的科目，因為我很愛畫畫。"),
    ("w140", "I put my books in my backpack.", "backpack", "我把書放進背包裡。"),
    ("w141", "Please put the old paper in the bin.", "bin", "請把舊紙丟進垃圾桶。"),
    ("w142", "I won first prize in the drawing competition.", "competition", "我在繪畫比賽中得到第一名。"),
    ("w143", "Look up the word in your dictionary.", "dictionary", "用你的字典查這個字。"),
    ("w144", "There's a flag on the castle.", "flag", "城堡上有一面旗子。"),
    ("w145", "In geography, we learn about rivers and mountains.", "geography", "我們在地理課學習河流和山脈。"),
    ("w146", "Glue the picture on the paper.", "Glue", "把圖片黏在紙上。"),
    ("w147", "We worked in a group of four.", "group", "我們四個人一組一起做。"),
    ("w148", "We play basketball in the school gym.", "gym", "我們在學校體育館打籃球。"),
    ("w149", "In history, we learn about people from the past.", "history", "我們在歷史課學習過去的人。"),
    ("w150", "English is an important language.", "language", "英文是一種重要的語言。"),
    ("w151", "We've got maths after lunch.", "maths", "我們午餐後有數學課。"),
    ("w152", "I like playing games online with my friends.", "online", "我喜歡和朋友一起在網路上玩遊戲。"),
    ("w153", "Our class is doing a project about the ocean.", "project", "我們班正在做一個關於海洋的專題。"),
    ("w154", "We learn about plants and animals in science.", "science", "我們在自然課學習植物和動物。"),
    ("w155", "Cut the paper with your scissors.", "scissors", "用你的剪刀剪紙。"),
    ("w156", "There are thirty students in my class.", "students", "我們班上有三十個學生。"),
    ("w157", "I need to study tonight because I've got an English quiz tomorrow.", "study", "我今晚要讀書，因為明天有英文小考。"),
    ("w158", "What's your favourite subject at school?", "subject", "你在學校最喜歡什麼科目？"),
    ("w159", "Look at the timetable. We've got music after lunch.", "timetable", "看看課表，我們午餐後有音樂課。"),
]
